### ISSUE TITLE
ECSS Stats HK unresponsive

### ISSUE THREAD

**Issue by ppapadeas** [librespacefoundation/upsat-eps-software#45]
Assertion 36:37 (?) occurs.

**Comment by ppapadeas** [comment]
Most possibly an ecss_service repo issue though.

**Comment by squarewavesbelow** [comment]
Is this something we can reproduce?
Please try with the last version. There might be a failure tht the watchdog couldnt catch rendering the eps subystem unresponsive.

**Comment by ppapadeas** [comment]
This is because packet is more than 198 bytes so it is blocked. Not deemed critical so we let is as is.
